substitutions:
  name: "apollo-m1-r4"
  friendly_name: "Apollo M-1"

  # ===== Display / Panel =====
  DISPLAY_CHAIN_LEN: "1" # Total number of panels you have connected
  DISPLAY_W: "64"  # Most likely 64 * ${DISPLAY_CHAIN_LEN}
  DISPLAY_H: "64"  # Most likely 64

  # Note: some variables need to be configured at the page level down below

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

logger:

api:

ota:
  platform: esphome

wifi:
  power_save_mode: none
  ap:

captive_portal:

packages:
  remote_package_files:
    url: https://github.com/stuartparmenter/apollo-m1-playground
    ref: main
    refresh: 0s
    files:
      # Base board/pins, LVGL root, services, etc.
      - path: packages/controllers/apollo-automation-m1-rev4.yaml

      # Shared helpers, sensors, buttons
      - path: packages/common/utils.yaml

      # Shared fonts and LVGL styles
      - path: packages/common/theme.yaml

      # Shared DDP and DDP websocket control config
      # Note: This is required by "Now Playing" and the "DDP Stream" pages
      - path: packages/common/ddp.yaml
        vars:
          DDP_PORT: "4048"
          WS_DDP_HOST: "homeassistant.local"
          WS_DDP_PORT: "8788"

      # Basic Boot Screen to avoid flashing or things not being ready yet
      - path: packages/pages/bios.yaml

      # Simple clock page
      - path: packages/pages/clock.yaml

      # Clock weather / dashboard
      - path: packages/pages/clock-dashboard.yaml
        vars:
          WX_ENTITY: "weather.home"
          HIGH_ENTITY: "sensor.weather_today_high"
          LOW_ENTITY:  "sensor.weather_today_low"
          ALARM_ENTITY: "alarm_control_panel.example_alarm"
          PERSON_A: "person.person_a"
          PERSON_B: "person.person_b"
          PERSON_A_ICON: "\U000F040A"  # account-circle
          PERSON_B_ICON: "\U000F0B8F"  # account-circle-outline

      # "Now Playing" media player page
      # - path: packages/pages/now-playing.yaml
      #   vars:
      #     HA_BASE_URL: "http://homeassistant.local:8123"  # Used to get preview images
      #     MEDIA_PLAYER_ENTITY: "media_player.your_media_player"

      # Page that uses lvgl-canvas-fx to render various effects (and change which in HA)
      - path: packages/pages/fx.yaml

      # A classic
      # - path: packages/pages/pong.yaml

      # Visualize your Apollo Automation MSR-2
      # - path: packages/pages/msr-2-radar.yaml
      #   vars:
      #     MSR2_PREFIX: "apollo_msr_2_xxxxxx"

      # DDP video streaming
      - path: packages/pages/ddp-stream.yaml
        vars:
          BACK_BUFFERS: 0  # 0-2
          DEFAULT_VIDEO_SRC: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"

# If you want to support non-horizontal layouts, you can uncomment this section below:
# display:
#   - id: !extend matrix
#     virtual_matrix:
#       enabled: true
#       rows: 2           # number of panel rows
#       cols: 1           # number of panel columns
#       chain_type: CHAIN_BOTTOM_RIGHT_UP   # layout mapping type
#       scan_type: STANDARD_TWO_SCAN        # typical scan type; adjust if your panels are unusual
