substitutions:
  name: "apollo-m1-r4"
  friendly_name: "Apollo M-1"

  # ===== Display / Panel =====
  DISPLAY_CHAIN_LEN: "1" # Total number of panels you have connected
  DISPLAY_W: "64"  # Most likely 64 * ${DISPLAY_CHAIN_LEN}
  DISPLAY_H: "64"  # Most likely 64

  # ===== DDP/WS Stream (used by Now Playing & DDP pages) =====
  WS_DDP_HOST: "192.168.1.200"
  WS_DDP_PORT: "8788"
  DDP_PORT: "4048"

  # ===== MSR2 Radar Screen (has to be up here because of how it is used in the page) =====
  # MSR2_PREFIX: "apollo_msr_2_xxxxxx"

  # Note: some variables need to be configured at the page level down below

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

logger:

api:

ota:
  platform: esphome

wifi:
  power_save_mode: none
  ap:

captive_portal:

packages:
  remote_package_files:
    url: https://github.com/stuartparmenter/apollo-m1-playground
    ref: main
    refresh: 0s
    files:
      # Base board/pins, LVGL root, services, etc.
      - path: packages/controller-rev4.yaml

      # Shared helpers, sensors, buttons
      - path: packages/common-utils.yaml

      # Shared fonts and LVGL styles
      - path: packages/common-theme.yaml

      # Basic Boot Screen to avoid flashing or things not being ready yet
      - path: packages/page-bios.yaml

      # Simple clock page
      - path: packages/page-clock.yaml

      # Clock weather / dashboard
      - path: packages/page-clock-dashboard.yaml
        vars:
          WX_ENTITY: "weather.home"
          HIGH_ENTITY: "sensor.weather_today_high"
          LOW_ENTITY:  "sensor.weather_today_low"
          ALARM_ENTITY: "alarm_control_panel.example_alarm"
          PERSON_A: "person.person_a"
          PERSON_B: "person.person_b"
          PERSON_A_ICON: "\U000F040A"  # account-circle
          PERSON_B_ICON: "\U000F0B8F"  # account-circle-outline

      # "Now Playing" media player page
      # - path: packages/page-now-playing.yaml
      #   vars:
      #     HA_BASE_URL: "http://homeassistant.local:8123"  # Used to get preview images
      #     MEDIA_PLAYER_ENTITY: "media_player.your_media_player"

      # Page that uses lvgl-canvas-fx to render various effects (and change which in HA)
      - path: packages/page-fx.yaml

      # A classic
      # - path: packages/page-pong.yaml

      # Visualize your Apollo Automation MSR-2
      # - path: packages/page-msr-2-radar.yaml

      # DDP video streaming
      - path: packages/page-ddp-stream.yaml
        vars:
          DEFAULT_VIDEO_SRC: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"

# If you want to support non-horizontal layouts, you can uncomment this section below:
# display:
#   - id: !extend matrix
#     virtual_matrix:
#       enabled: true
#       rows: 2           # number of panel rows
#       cols: 1           # number of panel columns
#       chain_type: CHAIN_BOTTOM_RIGHT_UP   # layout mapping type
#       scan_type: STANDARD_TWO_SCAN        # typical scan type; adjust if your panels are unusual
