# © Copyright 2025 Stuart Parmenter
# SPDX-License-Identifier: MIT

esphome:
  includes:
    - src/page_fireworks.h

lvgl:
  pages:
    - id: fireworks
      widgets:
        - obj:
            id: fw_layer
            width: 100%
            height: 100%

      on_load:
        then:
          - lambda: |-
              fireworks_on_load(id(fw_layer));

      on_unload:
        then:
          - lambda: |-
              fireworks_on_unload(id(fw_layer));
